#!/usr/bin/env bash
set -e

read -rp "Install directory (leave blank to use current directory): " install_dir

install_dir="${install_dir/#\~/$HOME}"

if [ -z "$install_dir" ]; then
    install_dir="$PWD"
    echo "Using current directory: $install_dir"
fi

if [ ! -d "$install_dir" ]; then
    echo "Directory doesn’t exist. Making it for you."
    mkdir -p "$install_dir"
fi

cd "$install_dir"

echo "Downloading files..."

wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/git/bulk/all-pull
chmod +x all-pull
wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/git/bulk/all-push
chmod +x all-push
wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/git/bulk/all-status
chmod +x all-status

wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/git/repo/pull
chmod +x pull
wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/git/repo/push
chmod +x push
wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/git/repo/status
chmod +x status

echo "Files downloaded"

read -rp "Copy pull/push/status to $HOME for quick access anywhere? [y/N]: " choice

case "$choice" in
    [yY])
        echo "Copying to $HOME directory..."
        cp -f pull push status "$HOME/"
        ;;
    *)
        echo "Skipping copy to home directory."
        ;;
esac

echo "All done!"
