#!/usr/bin/env bash

set -e

all_empty=true

for f in */.git/info/exclude; do
  if [[ -f "$f" ]]; then
    : > "$f"

    if [[ -s "$f" ]]; then
      echo "Warning: $f is not empty after wiping!"
      all_empty=false
    fi
  fi
done

if $all_empty; then
  echo "All exclude files emptied successfully."
fi

# Hang

echo
read -p "Press Enter to exit / Type 'disable' to disable hanging: " response

if [ "$response" = "disable" ]; then
    sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$0"
    echo
    echo "KEEP_OPEN set to false"
    sleep 4
fi
