#!/usr/bin/env bash

set -e

git add .
git status

# Hang

echo
read -p "Press Enter to exit / Type 'disable' to disable hanging: " response

KEEP_OPEN=true

if [ "$response" = "disable" ]; then
    sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$0"
    echo
    echo "KEEP_OPEN set to false"
    sleep 4
fi
