#!/usr/bin/env bash

set -e

for author in */; do
    [ -d "$author" ] || continue
    for repo in "$author"*/; do
        if [ -d "$repo/.git" ]; then
            echo "Pulling $repo"
            (
                cd "$repo"
                if git pull >/dev/null 2>&1; then
                    echo "Successfully pulled $repo"
                else
                    echo "Failed to pull $repo"
                fi
            ) &
        fi
    done
done

echo

wait

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging (local only): " response
    if [ "$response" = "disable" ]; then
        SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$SCRIPT_PATH"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        echo
        for i in {5..1}; do
            echo -n "Exiting in $i..."
            sleep 1
            echo -ne "\r"
        done
        echo "Exiting now.        "
    fi
fi
