#!/usr/bin/env bash

set -e

# This is used for the Hang at the end, for disabling it.
SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")

files=("$@")

if [ ${#files[@]} -eq 0 ]; then
    read -rp "Enter file(s) to sort: " -a files
fi

if [ ${#files[@]} -eq 0 ]; then
    echo "No files provided."
    exit 1
fi

for file in "${files[@]}"; do
    if [ ! -f "$file" ]; then
        echo "Error: '$file' is not a file."
        exit 1
    fi

    sort "$file" -o "$file"
done

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging (local only): " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$SCRIPT_PATH"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        echo
        for i in {5..1}; do
            echo -n "Exiting in $i..."
            sleep 1
            echo -ne "\r"
        done
        echo "Exiting now.        "
    fi
fi
